kind: Service
apiVwersion: v1
metadata:
  name: notes-app-service
  namespace: notes-app
  labels:
    app: notes-app
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8000      
      targetPort: 8000
